### ISSUE TITLE
Docker Image with PHP7 issues

### ISSUE THREAD

**Issue by thesugarat** [FredBardin/phpMyHue#13]
Hello,
Loved the concept so much I stuck it in a Docker Image. But.... it just doesn't look right. I'm using a base image that has PHP 7 in it. Any suggestions on a version of PHP that has the best compatibility? Or would you mind looking at the Image? https://hub.docker.com/r/allenscloud/phpmyhuealpine 

Thanks,

Allen

**Comment by FredBardin** [comment]
Hello,
I really enjoy seeing my hue project built into a docker image, thank you for the job.

To partially answer you, the dev is made with php 7, it couldn't be a compatibility issue with that.
I think it's more an issue with the browser you use or maybe the image if something works wrong on it.
For the browser : I made my tests with firefox, chrome and safari (i give up ie, too much problems).

I'll install a docker client on my dev computer to see how your image works, but if you can tell me which browser you use and give me some screenshots of your display problem it could help.

**Comment by thesugarat** [comment]
I'm actually using Firefox and I think I know why it looks different. I have several other apps that do effects for certain holidays and events. It appears those apps have created different light groups with strange longer names. 
![Capture1](https://user-images.githubusercontent.com/4702743/70156971-5a001f00-167a-11ea-9410-78ed028f58fb.JPG)
![Capture2](https://user-images.githubusercontent.com/4702743/70156972-5a001f00-167a-11ea-9e96-4b69e02512a4.JPG)
![Capture3](https://user-images.githubusercontent.com/4702743/70156973-5a001f00-167a-11ea-8d26-05f48f0193e5.JPG)

So I'm assuming there's nothing wrong with it... and it's just my settings. But I can think of three things you might be able to help with.
1. Is there code where you could you make the box autosize to all the text? 
2. As a docker container I can't run it in the network bridge mode because it scans the bridge network looking for the Hue Bridge which it will never find.  Do you know a way to have the user specify which IP address Range should be scanned for finding the Hue Bridge?
3. There's some sort of permissions issue where once it finds the Hue Bridge it can't write the proper config files. I'm going to work on this myself but if you see something I've missed, please let me know.

I plan to make a YouTube video about creating this Docker Image and of course will be linking to your github for the source code...

**Comment by FredBardin** [comment]
Hello, got it.

Indeed, if you have an unbreakable name somewhere in a list, it could mess up the display if it's too long.
The panels have a fixed width to control their internal look and also to always see, as much as possible, the details panel just right the menu/selection panel without any scrolling. I'm sorry, it couldn't be changed.

The solution is to include some spaces in your names so that it could be breakable on several lines.
The vertical autosizing is perfectly managed but you need to adapt your names
I did it in my configuration for some group, lamp, effects, ... It's the way it was designed.  

For your 2 other points : 

- Bridge auto-discover from docker image : 
My code comment : "_It's assumed that bridge is on the same sub-network with subnet mask 255.255.255.0_"
So, it's not currently possible, but displaying the base network to confirm it or change it could be the solution.
Some other ways exist to detect a bridge (ie upnp), but the network scanning allow to keep a light code.

- Write authorization : the user running your web server must have a right access on your phpmyhue directory or at least on the "include" sub directory.

**Comment by FredBardin** [comment]
Release pmh1.7.1 published : change of subnet value in automatic configuration is now possilble.
This solves the problem of auto-discover from a docker container.

I'll close the issue next week.

Don't hesitate if you have any other questions.

**Comment by thesugarat** [comment]
Thanks! I'll check out this new version and make a 2.0 version of the Docker image. I appreciate your help.
