### ISSUE TITLE
language: german

### ISSUE THREAD

**Issue by Klein-at-GitHub** [FredBardin/phpMyHue#14]
I'm comming from Germany.

Are you interested in a german translation:   text_de.json ?

Norbert Klein

**Comment by Klein-at-GitHub** [comment]
Hi Fred,
I translated it.
I saw your wiki today and will send the language file via issue.
Norbert

**Comment by FredBardin** [comment]
Hi Norbert,

There's no attached json since your last post.
Is it normal ?

**Comment by Klein-at-GitHub** [comment]
Hello Fred,
I translated your english file.
Yet I have not used or tried all functions of phpMyHue.
So I'm not sure, that all my translation are correct.
I added my E-Mail address at the end of the translated file - have a look at this and decide to use this information or delete the line.
[text_de.zip](https://github.com/FredBardin/phpMyHue/files/5362059/text_de.zip)

Thanks for your answer
Norbert

**Comment by FredBardin** [comment]
Hello Norbert,

Thank you for you file.
The translator field is a good idea, I'll integrate it in the "about" tab and will add an instruction in the wiki.

All fields seem almost ok (my german is weak ;)) and are displaying correctly in the interface.

I only notice a misunderstood : Group/group are identical, it's a case switch (so -> Gruppe/gruppe)
There're also some missing translations : 
- All lamps => Alle lampen
- all the values prefixed by 'x ' (3 values)
- Rules management by sensor
- Problem for updating the configuration file

In order to add your file in the package, could you please complete the missing translations ?

**Comment by Klein-at-GitHub** [comment]
Hello Fred,

next try :-)

translated !
[text_de.zip](https://github.com/FredBardin/phpMyHue/files/5371469/text_de.zip)


Norbert

**Comment by FredBardin** [comment]
Hello Norbert,

v1.7.2 released with your translation ;)
I added "TranslationAuthor" and "Translation" as new entries at the beginning of your lang file.
it's used in the about tab.

Thanks again for your contribution.
